name: Unit Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: apt update
      run: sudo apt update
      shell: bash

    - name: Install dependencies
      run: |
           sudo apt install clang-17
           sudo apt install libboost-all-dev
           sudo apt install libreadline-dev
      shell: bash

    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        ref: 'rewrite'
        submodules: recursive

    - name: Test
      working-directory: ${{github.workspace}}
      shell: bash
      run: ./tests.sh
      env:
        CHARLYVMDIR: ${{github.workspace}}
