name: Unit Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install clang-10
      run:  |
            sudo apt update
            sudo apt install clang-10
            sudo apt install libboost-all-dev
      shell: bash

    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        ref: 'rewrite'
        submodules: recursive

    - name: Test
      working-directory: ${{github.workspace}}
      shell: bash
      run: ./tests.sh
      env:
        CHARLYVMDIR: ${{github.workspace}}
